/**
 * MCU Marathon Tracker - Database
 * Contains detailed metadata for all 51 Marvel Cinematic Universe titles.
 */

const MCU_DATA = [
  // --- PHASE 1 (INFINITY SAGA) ---
  {
    id: "iron-man",
    title: "Iron Man",
    type: "movie",
    phase: 1,
    releaseDate: "2008-05-02",
    chronologicalOrder: 3,
    runtime: 126,
    ratingIMDb: 7.9,
    ratingRT: 94,
    director: "Jon Favreau",
    postCredits: 1,
    characters: ["Tony Stark", "Pepper Potts", "James Rhodes", "Obadiah Stane", "Nick Fury"],
    synopsis: "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.",
    coverGradient: "linear-gradient(135deg, #c1272d, #f5c518)"
  },
  {
    id: "the-incredible-hulk",
    title: "The Incredible Hulk",
    type: "movie",
    phase: 1,
    releaseDate: "2008-06-13",
    chronologicalOrder: 5,
    runtime: 112,
    ratingIMDb: 6.6,
    ratingRT: 67,
    director: "Louis Leterrier",
    postCredits: 1,
    characters: ["Bruce Banner", "Betty Ross", "Emil Blonsky / Abomination", "General Ross"],
    synopsis: "Bruce Banner, a scientist on the run from the U.S. Government, must find a cure for the monster he turns into in times of anger.",
    coverGradient: "linear-gradient(135deg, #1e7a43, #2d3e50)"
  },
  {
    id: "iron-man-2",
    title: "Iron Man 2",
    type: "movie",
    phase: 1,
    releaseDate: "2010-05-07",
    chronologicalOrder: 4,
    runtime: 124,
    ratingIMDb: 6.9,
    ratingRT: 71,
    director: "Jon Favreau",
    postCredits: 1,
    characters: ["Tony Stark", "Pepper Potts", "Natasha Romanoff / Black Widow", "Ivan Vanko / Whiplash", "Justin Hammer"],
    synopsis: "With the world now aware of his identity as Iron Man, Tony Stark must contend with both his declining health and a vengeful madman.",
    coverGradient: "linear-gradient(135deg, #b21f24, #a0a0a0)"
  },
  {
    id: "thor",
    title: "Thor",
    type: "movie",
    phase: 1,
    releaseDate: "2011-05-06",
    chronologicalOrder: 6,
    runtime: 115,
    ratingIMDb: 7.0,
    ratingRT: 77,
    director: "Kenneth Branagh",
    postCredits: 1,
    characters: ["Thor Odinson", "Loki Laufeyson", "Jane Foster", "Odin", "Heimdall"],
    synopsis: "The powerful but arrogant god Thor is cast out of Asgard to live amongst humans on Earth, where he becomes one of their finest defenders.",
    coverGradient: "linear-gradient(135deg, #1c75bc, #f5f2d0)"
  },
  {
    id: "captain-america-first-avenger",
    title: "Captain America: The First Avenger",
    type: "movie",
    phase: 1,
    releaseDate: "2011-07-22",
    chronologicalOrder: 1,
    runtime: 124,
    ratingIMDb: 6.9,
    ratingRT: 80,
    director: "Joe Johnston",
    postCredits: 1,
    characters: ["Steve Rogers", "Peggy Carter", "Bucky Barnes", "Johann Schmidt / Red Skull", "Howard Stark"],
    synopsis: "Steve Rogers, a rejected military soldier, transforms into Captain America after taking a dose of standard Super-Soldier serum during WWII.",
    coverGradient: "linear-gradient(135deg, #0f2c59, #a62626)"
  },
  {
    id: "the-avengers",
    title: "Marvel's The Avengers",
    type: "movie",
    phase: 1,
    releaseDate: "2012-05-04",
    chronologicalOrder: 7,
    runtime: 143,
    ratingIMDb: 8.0,
    ratingRT: 91,
    director: "Joss Whedon",
    postCredits: 2,
    characters: ["Steve Rogers", "Tony Stark", "Thor Odinson", "Bruce Banner", "Natasha Romanoff", "Clint Barton", "Loki Laufeyson"],
    synopsis: "Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army.",
    coverGradient: "linear-gradient(135deg, #0e1e38, #f5c518)"
  },

  // --- PHASE 2 (INFINITY SAGA) ---
  {
    id: "iron-man-3",
    title: "Iron Man 3",
    type: "movie",
    phase: 2,
    releaseDate: "2013-05-03",
    chronologicalOrder: 8,
    runtime: 130,
    ratingIMDb: 7.1,
    ratingRT: 79,
    director: "Shane Black",
    postCredits: 1,
    characters: ["Tony Stark", "Pepper Potts", "Aldrich Killian", "Happy Hogan", "Colonel Rhodes"],
    synopsis: "When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuild and retribution.",
    coverGradient: "linear-gradient(135deg, #991f24, #1a1a1a)"
  },
  {
    id: "thor-dark-world",
    title: "Thor: The Dark World",
    type: "movie",
    phase: 2,
    releaseDate: "2013-11-08",
    chronologicalOrder: 9,
    runtime: 112,
    ratingIMDb: 6.8,
    ratingRT: 67,
    director: "Alan Taylor",
    postCredits: 2,
    characters: ["Thor Odinson", "Loki Laufeyson", "Jane Foster", "Malekith", "Odin"],
    synopsis: "When the Dark Elves attempt to plunge the universe into darkness, Thor must embark on a perilous and personal journey.",
    coverGradient: "linear-gradient(135deg, #1b3d54, #734f37)"
  },
  {
    id: "captain-america-winter-soldier",
    title: "Captain America: The Winter Soldier",
    type: "movie",
    phase: 2,
    releaseDate: "2014-04-04",
    chronologicalOrder: 10,
    runtime: 136,
    ratingIMDb: 7.8,
    ratingRT: 90,
    director: "Anthony and Joe Russo",
    postCredits: 2,
    characters: ["Steve Rogers", "Natasha Romanoff", "Sam Wilson / Falcon", "Bucky Barnes / Winter Soldier", "Nick Fury"],
    synopsis: "Steve Rogers struggles to embrace his role in the modern world and teams up with a fellow Avenger to battle a shadowy assassin.",
    coverGradient: "linear-gradient(135deg, #0b2240, #616a75)"
  },
  {
    id: "guardians-of-the-galaxy",
    title: "Guardians of the Galaxy",
    type: "movie",
    phase: 2,
    releaseDate: "2014-08-01",
    chronologicalOrder: 11,
    runtime: 121,
    ratingIMDb: 8.0,
    ratingRT: 92,
    director: "James Gunn",
    postCredits: 2,
    characters: ["Peter Quill / Star-Lord", "Gamora Zen", "Drax the Destroyer", "Rocket Raccoon", "Groot"],
    synopsis: "A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.",
    coverGradient: "linear-gradient(135deg, #b25329, #2b1f40)"
  },
  {
    id: "avengers-age-of-ultron",
    title: "Avengers: Age of Ultron",
    type: "movie",
    phase: 2,
    releaseDate: "2015-05-01",
    chronologicalOrder: 12,
    runtime: 141,
    ratingIMDb: 7.3,
    ratingRT: 76,
    director: "Joss Whedon",
    postCredits: 1,
    characters: ["Tony Stark", "Steve Rogers", "Thor", "Bruce Banner", "Wanda Maximoff", "Pietro Maximoff", "Ultron"],
    synopsis: "When Tony Stark and Bruce Banner try to jumpstart a dormant peacekeeping program called Ultron, things go horribly wrong.",
    coverGradient: "linear-gradient(135deg, #8c1d1d, #425166)"
  },
  {
    id: "ant-man",
    title: "Ant-Man",
    type: "movie",
    phase: 2,
    releaseDate: "2015-07-17",
    chronologicalOrder: 13,
    runtime: 117,
    ratingIMDb: 7.2,
    ratingRT: 83,
    director: "Peyton Reed",
    postCredits: 2,
    characters: ["Scott Lang", "Hank Pym", "Hope van Dyne", "Darren Cross / Yellowjacket"],
    synopsis: "Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero.",
    coverGradient: "linear-gradient(135deg, #cc1c22, #212121)"
  },

  // --- PHASE 3 (INFINITY SAGA) ---
  {
    id: "captain-america-civil-war",
    title: "Captain America: Civil War",
    type: "movie",
    phase: 3,
    releaseDate: "2016-05-06",
    chronologicalOrder: 14,
    runtime: 147,
    ratingIMDb: 7.8,
    ratingRT: 91,
    director: "Anthony and Joe Russo",
    postCredits: 2,
    characters: ["Steve Rogers", "Tony Stark", "Bucky Barnes", "Natasha Romanoff", "T'Challa / Black Panther", "Peter Parker / Spider-Man"],
    synopsis: "Political involvement in the Avengers' affairs causes a rift between former allies Captain America and Iron Man.",
    coverGradient: "linear-gradient(135deg, #0d1b2a, #800e13)"
  },
  {
    id: "doctor-strange",
    title: "Doctor Strange",
    type: "movie",
    phase: 3,
    releaseDate: "2016-11-04",
    chronologicalOrder: 16,
    runtime: 115,
    ratingIMDb: 7.5,
    ratingRT: 89,
    director: "Scott Derrickson",
    postCredits: 2,
    characters: ["Stephen Strange", "Karl Mordo", "Ancient One", "Kaecilius", "Wong"],
    synopsis: "While on a physical and spiritual journey of healing, a brilliant neurosurgeon is drawn into the world of the mystic arts.",
    coverGradient: "linear-gradient(135deg, #5c2282, #0d3b66)"
  },
  {
    id: "guardians-of-the-galaxy-vol-2",
    title: "Guardians of the Galaxy Vol. 2",
    type: "movie",
    phase: 3,
    releaseDate: "2017-05-05",
    chronologicalOrder: 15,
    runtime: 136,
    ratingIMDb: 7.6,
    ratingRT: 85,
    director: "James Gunn",
    postCredits: 5,
    characters: ["Peter Quill / Star-Lord", "Gamora", "Drax", "Rocket", "Baby Groot", "Ego"],
    synopsis: "The Guardians struggle to keep together as a team while helping Peter Quill learn more about his mysterious, celestial parentage.",
    coverGradient: "linear-gradient(135deg, #1b7a95, #bf2665)"
  },
  {
    id: "spider-man-homecoming",
    title: "Spider-Man: Homecoming",
    type: "movie",
    phase: 3,
    releaseDate: "2017-07-07",
    chronologicalOrder: 17,
    runtime: 133,
    ratingIMDb: 7.4,
    ratingRT: 92,
    director: "Jon Watts",
    postCredits: 2,
    characters: ["Peter Parker", "Adrian Toomes / Vulture", "Tony Stark", "Ned Leeds", "Michelle 'MJ' Jones"],
    synopsis: "Peter Parker balances his life as an ordinary high school student in Queens with his superhero alter-ego Spider-Man, under Tony Stark's guidance.",
    coverGradient: "linear-gradient(135deg, #c31432, #240b36)"
  },
  {
    id: "thor-ragnarok",
    title: "Thor: Ragnarok",
    type: "movie",
    phase: 3,
    releaseDate: "2017-11-03",
    chronologicalOrder: 18,
    runtime: 130,
    ratingIMDb: 7.9,
    ratingRT: 93,
    director: "Taika Waititi",
    postCredits: 2,
    characters: ["Thor Odinson", "Loki Laufeyson", "Hela", "Bruce Banner / Hulk", "Valkyrie", "Grandmaster"],
    synopsis: "Imprisoned on the planet Sakaar, Thor must race against time to return to Asgard and stop Ragnarok, the destruction of his world, at the hands of Hela.",
    coverGradient: "linear-gradient(135deg, #00f2fe, #4facfe)"
  },
  {
    id: "black-panther",
    title: "Black Panther",
    type: "movie",
    phase: 3,
    releaseDate: "2018-02-16",
    chronologicalOrder: 19,
    runtime: 134,
    ratingIMDb: 7.3,
    ratingRT: 96,
    director: "Ryan Coogler",
    postCredits: 2,
    characters: ["T'Challa / Black Panther", "Erik Killmonger", "Nakia", "Okoye", "Shuri"],
    synopsis: "T'Challa, heir to the hidden kingdom of Wakanda, must step forward to lead his people into a new era and confront a challenger from his country's past.",
    coverGradient: "linear-gradient(135deg, #0f0c20, #c5a059)"
  },
  {
    id: "avengers-infinity-war",
    title: "Avengers: Infinity War",
    type: "movie",
    phase: 3,
    releaseDate: "2018-04-27",
    chronologicalOrder: 20,
    runtime: 149,
    ratingIMDb: 8.4,
    ratingRT: 85,
    director: "Anthony and Joe Russo",
    postCredits: 1,
    characters: ["Thanos", "Tony Stark", "Steve Rogers", "Thor", "Bruce Banner", "Wanda Maximoff", "Stephen Strange", "Peter Quill"],
    synopsis: "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation ends the universe.",
    coverGradient: "linear-gradient(135deg, #511c74, #b4274c)"
  },
  {
    id: "ant-man-and-the-wasp",
    title: "Ant-Man and the Wasp",
    type: "movie",
    phase: 3,
    releaseDate: "2018-07-06",
    chronologicalOrder: 21,
    runtime: 118,
    ratingIMDb: 7.0,
    ratingRT: 87,
    director: "Peyton Reed",
    postCredits: 2,
    characters: ["Scott Lang", "Hope van Dyne / Wasp", "Hank Pym", "Ava Starr / Ghost", "Janet van Dyne"],
    synopsis: "As Scott Lang balances being both a superhero and a father, Hope van Dyne and Dr. Hank Pym present an urgent new mission to enter the Quantum Realm.",
    coverGradient: "linear-gradient(135deg, #f12711, #f5af19)"
  },
  {
    id: "captain-marvel",
    title: "Captain Marvel",
    type: "movie",
    phase: 3,
    releaseDate: "2019-03-08",
    chronologicalOrder: 2,
    runtime: 124,
    ratingIMDb: 6.8,
    ratingRT: 79,
    director: "Anna Boden and Ryan Fleck",
    postCredits: 2,
    characters: ["Carol Danvers / Captain Marvel", "Nick Fury", "Talos", "Yon-Rogg", "Maria Rambeau"],
    synopsis: "Carol Danvers becomes one of the universe's most powerful heroes when Earth is caught in the middle of a galactic war between two alien races.",
    coverGradient: "linear-gradient(135deg, #103463, #cc1f2c)"
  },
  {
    id: "avengers-endgame",
    title: "Avengers: Endgame",
    type: "movie",
    phase: 3,
    releaseDate: "2019-04-26",
    chronologicalOrder: 22,
    runtime: 181,
    ratingIMDb: 8.4,
    ratingRT: 94,
    director: "Anthony and Joe Russo",
    postCredits: 0,
    characters: ["Tony Stark", "Steve Rogers", "Thor", "Bruce Banner", "Natasha Romanoff", "Clint Barton", "Thanos"],
    synopsis: "After the devastating events of Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more to reverse Thanos' actions.",
    coverGradient: "linear-gradient(135deg, #09090e, #3a1c71)"
  },
  {
    id: "spider-man-far-from-home",
    title: "Spider-Man: Far From Home",
    type: "movie",
    phase: 3,
    releaseDate: "2019-07-02",
    chronologicalOrder: 23,
    runtime: 129,
    ratingIMDb: 7.4,
    ratingRT: 90,
    director: "Jon Watts",
    postCredits: 2,
    characters: ["Peter Parker", "Quentin Beck / Mysterio", "Nick Fury", "MJ", "Ned Leeds"],
    synopsis: "Following the events of Endgame, Spider-Man must step up to take on new threats in a world that has changed forever.",
    coverGradient: "linear-gradient(135deg, #141e30, #243b55)"
  },

  // --- PHASE 4 (MULTIVERSE SAGA) ---
  {
    id: "wandavision",
    title: "WandaVision",
    type: "series",
    phase: 4,
    releaseDate: "2021-01-15",
    chronologicalOrder: 24,
    runtime: 350,
    ratingIMDb: 7.9,
    ratingRT: 91,
    director: "Matt Shakman",
    postCredits: 3,
    characters: ["Wanda Maximoff", "Vision", "Agatha Harkness", "Monica Rambeau", "Jimmy Woo"],
    synopsis: "Blends the style of classic sitcoms with the Marvel Cinematic Universe in which Wanda Maximoff and Vision live idealized suburban lives.",
    coverGradient: "linear-gradient(135deg, #c31432, #ffd700)"
  },
  {
    id: "falcon-swinter-soldier",
    title: "The Falcon and the Winter Soldier",
    type: "series",
    phase: 4,
    releaseDate: "2021-03-19",
    chronologicalOrder: 25,
    runtime: 300,
    ratingIMDb: 7.2,
    ratingRT: 84,
    director: "Kari Skogland",
    postCredits: 2,
    characters: ["Sam Wilson / Captain America", "Bucky Barnes", "John Walker", "Karli Morgenthau", "Helmut Zemo"],
    synopsis: "Following the events of Endgame, Sam Wilson and Bucky Barnes team up in a global adventure that tests their abilities and their patience.",
    coverGradient: "linear-gradient(135deg, #16222f, #bf3f3f)"
  },
  {
    id: "loki-season-1",
    title: "Loki (Season 1)",
    type: "series",
    phase: 4,
    releaseDate: "2021-06-09",
    chronologicalOrder: 26,
    runtime: 290,
    ratingIMDb: 8.2,
    ratingRT: 92,
    director: "Kate Herron",
    postCredits: 1,
    characters: ["Loki Laufeyson", "Mobius M. Mobius", "Sylvie", "Ravonna Renslayer", "He Who Remains"],
    synopsis: "The mercurial villain Loki resumes his role as the God of Mischief in a new series that takes place after the events of Avengers: Endgame.",
    coverGradient: "linear-gradient(135deg, #1b4d3e, #f5af19)"
  },
  {
    id: "black-widow",
    title: "Black Widow",
    type: "movie",
    phase: 4,
    releaseDate: "2021-07-09",
    chronologicalOrder: 27,
    runtime: 134,
    ratingIMDb: 6.7,
    ratingRT: 79,
    director: "Cate Shortland",
    postCredits: 1,
    characters: ["Natasha Romanoff", "Yelena Belova", "Alexei Shostakov / Red Guardian", "Melina Vostokoff", "Dreykov"],
    synopsis: "A film confronting the darker parts of Natasha Romanoff's ledger when a dangerous conspiracy with ties to her past arises.",
    coverGradient: "linear-gradient(135deg, #09090b, #ed1d24)"
  },
  {
    id: "what-if-season-1",
    title: "What If...? (Season 1)",
    type: "series",
    phase: 4,
    releaseDate: "2021-08-11",
    chronologicalOrder: 28,
    runtime: 280,
    ratingIMDb: 7.4,
    ratingRT: 94,
    director: "Bryan Andrews",
    postCredits: 0,
    characters: ["The Watcher", "Peggy Carter / Captain Carter", "T'Challa Star-Lord", "Doctor Strange Supreme"],
    synopsis: "Exploring pivotal moments from the Marvel Cinematic Universe and turning them on their head, leading the audience into uncharted territory.",
    coverGradient: "linear-gradient(135deg, #200122, #6f0000)"
  },
  {
    id: "shang-chi",
    title: "Shang-Chi and the Legend of the Ten Rings",
    type: "movie",
    phase: 4,
    releaseDate: "2021-09-03",
    chronologicalOrder: 29,
    runtime: 132,
    ratingIMDb: 7.4,
    ratingRT: 91,
    director: "Destin Daniel Cretton",
    postCredits: 2,
    characters: ["Shang-Chi", "Katy Chen", "Xu Wenwu / The Mandarin", "Xu Xialing", "Ying Li"],
    synopsis: "Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.",
    coverGradient: "linear-gradient(135deg, #81171b, #d9a05b)"
  },
  {
    id: "eternals",
    title: "Eternals",
    type: "movie",
    phase: 4,
    releaseDate: "2021-11-05",
    chronologicalOrder: 30,
    runtime: 156,
    ratingIMDb: 6.3,
    ratingRT: 47,
    director: "Chloé Zhao",
    postCredits: 2,
    characters: ["Sersi", "Ikaris", "Thena", "Kingo", "Phastos", "Sprite", "Druig", "Ajak"],
    synopsis: "The saga of the Eternals, a race of immortal beings who lived on Earth and shaped its history and civilizations.",
    coverGradient: "linear-gradient(135deg, #0f1c24, #bfa054)"
  },
  {
    id: "hawkeye",
    title: "Hawkeye",
    type: "series",
    phase: 4,
    releaseDate: "2021-11-24",
    chronologicalOrder: 31,
    runtime: 290,
    ratingIMDb: 7.5,
    ratingRT: 92,
    director: "Rhys Thomas & Bert & Bertie",
    postCredits: 1,
    characters: ["Clint Barton / Hawkeye", "Kate Bishop", "Yelena Belova", "Maya Lopez", "Wilson Fisk / Kingpin"],
    synopsis: "Former Avenger Clint Barton has a seemingly simple mission: get back to his family for Christmas. Possible? With the help of an aspiring archer.",
    coverGradient: "linear-gradient(135deg, #3c1e5a, #200f35)"
  },
  {
    id: "spider-man-no-way-home",
    title: "Spider-Man: No Way Home",
    type: "movie",
    phase: 4,
    releaseDate: "2021-12-17",
    chronologicalOrder: 32,
    runtime: 148,
    ratingIMDb: 8.2,
    ratingRT: 93,
    director: "Jon Watts",
    postCredits: 2,
    characters: ["Peter Parker", "Stephen Strange", "Otto Octavius / Doc Ock", "Norman Osborn / Green Goblin", "Electro"],
    synopsis: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds appear.",
    coverGradient: "linear-gradient(135deg, #c31432, #0f2027)"
  },
  {
    id: "moon-knight",
    title: "Moon Knight",
    type: "series",
    phase: 4,
    releaseDate: "2022-03-30",
    chronologicalOrder: 33,
    runtime: 280,
    ratingIMDb: 7.3,
    ratingRT: 86,
    director: "Mohamed Diab",
    postCredits: 1,
    characters: ["Steven Grant / Marc Spector", "Layla El-Faouly / Scarlet Scarab", "Arthur Harrow"],
    synopsis: "Steven Grant discovers he's been gifted with the powers of an Egyptian moon god. But he soon finds out that these powers can be both a blessing and a curse.",
    coverGradient: "linear-gradient(135deg, #ece9e6, #585a5e)"
  },
  {
    id: "doctor-strange-multiverse-madness",
    title: "Doctor Strange in the Multiverse of Madness",
    type: "movie",
    phase: 4,
    releaseDate: "2022-05-06",
    chronologicalOrder: 34,
    runtime: 126,
    ratingIMDb: 6.9,
    ratingRT: 73,
    director: "Sam Raimi",
    postCredits: 2,
    characters: ["Stephen Strange", "Wanda Maximoff / Scarlet Witch", "America Chavez", "Wong", "Christine Palmer"],
    synopsis: "Doctor Strange journeys into the unknown with mystical allies, both old and new, traversing the mind-bending alternate realities of the Multiverse.",
    coverGradient: "linear-gradient(135deg, #4b1248, #f0c27b)"
  },
  {
    id: "ms-marvel",
    title: "Ms. Marvel",
    type: "series",
    phase: 4,
    releaseDate: "2022-06-08",
    chronologicalOrder: 35,
    runtime: 270,
    ratingIMDb: 6.3,
    ratingRT: 98,
    director: "Adil & Bilall",
    postCredits: 1,
    characters: ["Kamala Khan / Ms. Marvel", "Bruno Carrelli", "Kamran", "Muneeba Khan"],
    synopsis: "Kamala, a gaming geek and fan-fiction scribe, is a mega-fan of Captain Marvel. But she feels like she doesn't fit in at school and home—until she gets superpowers.",
    coverGradient: "linear-gradient(135deg, #ff007f, #7b1fa2)"
  },
  {
    id: "thor-love-and-thunder",
    title: "Thor: Love and Thunder",
    type: "movie",
    phase: 4,
    releaseDate: "2022-07-08",
    chronologicalOrder: 36,
    runtime: 118,
    ratingIMDb: 6.2,
    ratingRT: 63,
    director: "Taika Waititi",
    postCredits: 2,
    characters: ["Thor Odinson", "Jane Foster / Mighty Thor", "Gorr the God Butcher", "Valkyrie", "Korg"],
    synopsis: "Thor embarks on a journey unlike anything he's ever faced – a quest for inner peace. But his retirement is interrupted by a galactic killer.",
    coverGradient: "linear-gradient(135deg, #ff007f, #00f2fe)"
  },
  {
    id: "i-am-groot-season-1",
    title: "I Am Groot (Season 1)",
    type: "special",
    phase: 4,
    releaseDate: "2022-08-10",
    chronologicalOrder: 37,
    runtime: 20,
    ratingIMDb: 6.7,
    ratingRT: 88,
    director: "Kirsten Lepore",
    postCredits: 0,
    characters: ["Baby Groot", "Rocket Raccoon"],
    synopsis: "A collection of five shorts featuring Baby Groot, everyone's favorite little tree, showing his glory days growing up and getting into trouble.",
    coverGradient: "linear-gradient(135deg, #11998e, #38ef7d)"
  },
  {
    id: "she-hulk",
    title: "She-Hulk: Attorney at Law",
    type: "series",
    phase: 4,
    releaseDate: "2022-08-18",
    chronologicalOrder: 38,
    runtime: 270,
    ratingIMDb: 5.3,
    ratingRT: 77,
    director: "Kat Coiro",
    postCredits: 4,
    characters: ["Jennifer Walters / She-Hulk", "Nikki Ramos", "Emil Blonsky / Abomination", "Bruce Banner / Hulk", "Matt Murdock / Daredevil"],
    synopsis: "Jennifer Walters navigates the complicated life of a single, 30-something attorney who also happens to be a green 6-foot-7-inch superpowered hulk.",
    coverGradient: "linear-gradient(135deg, #0ba360, #3cba92)"
  },
  {
    id: "werewolf-by-night",
    title: "Werewolf by Night",
    type: "special",
    phase: 4,
    releaseDate: "2022-10-07",
    chronologicalOrder: 39,
    runtime: 53,
    ratingIMDb: 7.2,
    ratingRT: 89,
    director: "Michael Giacchino",
    postCredits: 0,
    characters: ["Jack Russell / Werewolf", "Elsa Bloodstone", "Ted / Man-Thing", "Verussa Stone"],
    synopsis: "On a dark and somber night, a secret cabal of monster hunters emerge from the shadows and gather at the foreboding Bloodstone Temple.",
    coverGradient: "linear-gradient(135deg, #000000, #333333)"
  },
  {
    id: "black-panther-wakanda-forever",
    title: "Black Panther: Wakanda Forever",
    type: "movie",
    phase: 4,
    releaseDate: "2022-11-11",
    chronologicalOrder: 40,
    runtime: 161,
    ratingIMDb: 7.2,
    ratingRT: 84,
    director: "Ryan Coogler",
    postCredits: 1,
    characters: ["Shuri / Black Panther", "Namor", "Queen Ramonda", "Okoye", "Riri Williams / Ironheart"],
    synopsis: "The leaders of Wakanda fight to protect their nation from invading world powers in the wake of King T'Challa's death.",
    coverGradient: "linear-gradient(135deg, #18002a, #4a154b)"
  },
  {
    id: "gotg-holiday-special",
    title: "The Guardians of the Galaxy Holiday Special",
    type: "special",
    phase: 4,
    releaseDate: "2022-11-25",
    chronologicalOrder: 41,
    runtime: 44,
    ratingIMDb: 6.9,
    ratingRT: 93,
    director: "James Gunn",
    postCredits: 1,
    characters: ["Mantis", "Drax the Destroyer", "Peter Quill / Star-Lord", "Kevin Bacon", "Nebula"],
    synopsis: "On a mission to make Christmas unforgettable for Quill, the Guardians head to Earth in search of the perfect present.",
    coverGradient: "linear-gradient(135deg, #11998e, #c02425)"
  },

  // --- PHASE 5 (MULTIVERSE SAGA) ---
  {
    id: "ant-man-quantumania",
    title: "Ant-Man and the Wasp: Quantumania",
    type: "movie",
    phase: 5,
    releaseDate: "2023-02-17",
    chronologicalOrder: 42,
    runtime: 124,
    ratingIMDb: 6.1,
    ratingRT: 46,
    director: "Peyton Reed",
    postCredits: 2,
    characters: ["Scott Lang / Ant-Man", "Hope van Dyne / Wasp", "Kang the Conqueror", "Cassie Lang", "Janet van Dyne"],
    synopsis: "Scott Lang and Hope Van Dyne, along with Hank Pym and Janet Van Dyne, explore the Quantum Realm, where they interact with strange creatures.",
    coverGradient: "linear-gradient(135deg, #2b1055, #7597de)"
  },
  {
    id: "gotg-vol-3",
    title: "Guardians of the Galaxy Vol. 3",
    type: "movie",
    phase: 5,
    releaseDate: "2023-05-05",
    chronologicalOrder: 43,
    runtime: 150,
    ratingIMDb: 7.9,
    ratingRT: 82,
    director: "James Gunn",
    postCredits: 2,
    characters: ["Rocket Raccoon", "Peter Quill / Star-Lord", "Gamora", "Nebula", "High Evolutionary", "Adam Warlock"],
    synopsis: "Still reeling from the loss of Gamora, Peter Quill rallies his team to defend the universe and protect one of their own – a mission that could mean the end.",
    coverGradient: "linear-gradient(135deg, #fc00ff, #00dbde)"
  },
  {
    id: "secret-invasion",
    title: "Secret Invasion",
    type: "series",
    phase: 5,
    releaseDate: "2023-06-21",
    chronologicalOrder: 44,
    runtime: 260,
    ratingIMDb: 5.5,
    ratingRT: 53,
    director: "Ali Selim",
    postCredits: 0,
    characters: ["Nick Fury", "Talos", "Gravik", "G'iah", "Sonya Falsworth"],
    synopsis: "Nick Fury learns of a clandestine invasion of Earth by a faction of shapeshifting Skrulls. Fury joins his allies, and together they race against time.",
    coverGradient: "linear-gradient(135deg, #2e4053, #196f3d)"
  },
  {
    id: "i-am-groot-season-2",
    title: "I Am Groot (Season 2)",
    type: "special",
    phase: 5,
    releaseDate: "2023-09-06",
    chronologicalOrder: 45,
    runtime: 20,
    ratingIMDb: 6.7,
    ratingRT: 90,
    director: "Kirsten Lepore",
    postCredits: 0,
    characters: ["Baby Groot", "The Watcher"],
    synopsis: "The troublemaking twig returns to his antics in five all-new adventures across the cosmos, exploring environments far beyond the Guardians' ship.",
    coverGradient: "linear-gradient(135deg, #11998e, #d4fc79)"
  },
  {
    id: "loki-season-2",
    title: "Loki (Season 2)",
    type: "series",
    phase: 5,
    releaseDate: "2023-10-05",
    chronologicalOrder: 46,
    runtime: 290,
    ratingIMDb: 8.2,
    ratingRT: 94,
    director: "Justin Benson & Aaron Moorhead",
    postCredits: 0,
    characters: ["Loki Laufeyson", "Mobius M. Mobius", "Sylvie", "Ouroboros 'OB'", "Victor Timely"],
    synopsis: "Loki navigates a constantly expanding and increasingly dangerous multiverse in search of Sylvie, Judge Renslayer, and Miss Minutes.",
    coverGradient: "linear-gradient(135deg, #0f3443, #34e89e)"
  },
  {
    id: "the-marvels",
    title: "The Marvels",
    type: "movie",
    phase: 5,
    releaseDate: "2023-11-10",
    chronologicalOrder: 47,
    runtime: 105,
    ratingIMDb: 5.6,
    ratingRT: 62,
    director: "Nia DaCosta",
    postCredits: 1,
    characters: ["Carol Danvers / Captain Marvel", "Kamala Khan / Ms. Marvel", "Monica Rambeau / Photon", "Dar-Benn"],
    synopsis: "Carol Danvers reclaims her identity from the tyrannical Kree. When her duties send her to an anomalous wormhole, her powers become entangled with Kamala Khan and Monica Rambeau.",
    coverGradient: "linear-gradient(135deg, #ff007f, #4a154b)"
  },
  {
    id: "what-if-season-2",
    title: "What If...? (Season 2)",
    type: "series",
    phase: 5,
    releaseDate: "2023-12-22",
    chronologicalOrder: 48,
    runtime: 280,
    ratingIMDb: 7.4,
    ratingRT: 89,
    director: "Bryan Andrews",
    postCredits: 0,
    characters: ["The Watcher", "Kahhori", "Peggy Carter", "Hela"],
    synopsis: "The Watcher continues his journey as our guide through the vast multiverse, introducing brand-new and familiar faces throughout the MCU.",
    coverGradient: "linear-gradient(135deg, #451254, #120f2e)"
  },
  {
    id: "echo",
    title: "Echo",
    type: "series",
    phase: 5,
    releaseDate: "2024-01-09",
    chronologicalOrder: 49,
    runtime: 170,
    ratingIMDb: 6.0,
    ratingRT: 71,
    director: "Sydney Freeland",
    postCredits: 1,
    characters: ["Maya Lopez / Echo", "Wilson Fisk / Kingpin", "Henry 'Black Crow' Lopez", "Matt Murdock / Daredevil"],
    synopsis: "Maya Lopez's ruthless behavior in New York City catches up with her in her hometown. She must face her past, reconnect with her Native American roots and embrace her family.",
    coverGradient: "linear-gradient(135deg, #090909, #8e0b0b)"
  },
  {
    id: "deadpool-and-wolverine",
    title: "Deadpool & Wolverine",
    type: "movie",
    phase: 5,
    releaseDate: "2024-07-26",
    chronologicalOrder: 50,
    runtime: 128,
    ratingIMDb: 7.7,
    ratingRT: 78,
    director: "Shawn Levy",
    postCredits: 1,
    characters: ["Wade Wilson / Deadpool", "Logan / Wolverine", "Cassandra Nova", "Paradox", "Peter"],
    synopsis: "Deadpool's peaceful life is interrupted when the Time Variance Authority recruits him to save his universe, teaming up with a reluctant Wolverine.",
    coverGradient: "linear-gradient(135deg, #a61c1c, #cca300)"
  },
  {
    id: "agatha-all-along",
    title: "Agatha All Along",
    type: "series",
    phase: 5,
    releaseDate: "2024-09-18",
    chronologicalOrder: 51,
    runtime: 310,
    ratingIMDb: 7.2,
    ratingRT: 83,
    director: "Jac Schaeffer",
    postCredits: 0,
    characters: ["Agatha Harkness", "Billy Maximoff / Teen", "Rio Vidal / Death", "Lilia Calderu", "Jennifer Kale"],
    synopsis: "A spell-bound Agatha Harkness regains freedom thanks to a goth teen's help. Without magic, she joins forces with a new coven to face the trials of the legendary Witches' Road.",
    coverGradient: "linear-gradient(135deg, #1b002c, #4a1254)"
  }
];

// Helper to calculate statistics
function getMCUStats(watchedIds = []) {
  const total = MCU_DATA.length;
  const watched = MCU_DATA.filter(item => watchedIds.includes(item.id)).length;
  const totalRuntime = MCU_DATA.reduce((acc, item) => acc + item.runtime, 0);
  const watchedRuntime = MCU_DATA.filter(item => watchedIds.includes(item.id))
                                 .reduce((acc, item) => acc + item.runtime, 0);

  const movies = MCU_DATA.filter(item => item.type === "movie");
  const series = MCU_DATA.filter(item => item.type === "series");
  const specials = MCU_DATA.filter(item => item.type === "special");

  return {
    total,
    watched,
    percentage: total > 0 ? Math.round((watched / total) * 100) : 0,
    totalRuntime,
    watchedRuntime,
    moviesCount: {
      total: movies.length,
      watched: movies.filter(item => watchedIds.includes(item.id)).length
    },
    seriesCount: {
      total: series.length,
      watched: series.filter(item => watchedIds.includes(item.id)).length
    },
    specialsCount: {
      total: specials.length,
      watched: specials.filter(item => watchedIds.includes(item.id)).length
    }
  };
}
